const TYPES = {
    AccountEntity: Symbol.for('AccountEntity'),
    AccountService: Symbol.for('AccountService'),
    AccountController: Symbol.for('AccountController'),
    CredentialEntity: Symbol.for('CredentialEntity'),
    CredentialService: Symbol.for('CredentialService'),
    CredentialController: Symbol.for('CredentialController'),
    RoleEntity: Symbol.for('RoleEntity'),
    RoleService: Symbol.for('RoleService'),
    RoleController: Symbol.for('RoleController'),
    ProfileEntity: Symbol.for('ProfileEntity'),
    ProfileService: Symbol.for('ProfileService'),
    ProfileController: Symbol.for('ProfileController'),
    ModelRoleEntity: Symbol.for('ModelRoleEntity'),
    ModelRoleService: Symbol.for('ModelRoleService'),
    ModelRoleController: Symbol.for('ModelRoleController'),
    ModelEntity: Symbol.for('ModelEntity'),
    ModelService: Symbol.for('ModelService'),
    ModelController: Symbol.for('ModelController'),
    RolePermissionEntity: Symbol.for('RolePermissionEntity'),
    RolePermissionService: Symbol.for('RolePermissioServicen'),
    RolePermissionController: Symbol.for('RolePermissionController'),
    ModelPermissionEntity: Symbol.for('ModelPermissionEntity'),
    ModelPermissionService: Symbol.for('ModelPermissionService'),
    ModelPermissionController: Symbol.for('ModelPermissionController'),
    PermissionEntity: Symbol.for('PermissionEntity'),
    PermissionService: Symbol.for('PermissionService'),
    PermissionController: Symbol.for('PermissionController'),
    IntegrationEntity: Symbol.for('IntegrationEntity'),
    IntegrationService: Symbol.for('IntegrationService'),
    IntegrationController: Symbol.for('IntegrationController'),
    AuthenticationService: Symbol.for('AuthenticationService'),
};

export { TYPES };